name: Main
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Generate Changelog
        run: echo "# Good things have arrived" > ${{ github.workspace }}-CHANGELOG.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
            name: 'OpenWrt Firmware'
            tag_name:  for test'
            token: ${{ secrets.GH_TOKEN }}
            files: ${{ github.workspace }}/configs/x86_64.config
            body: |
                **This is OpenWrt Firmware for **
                ### ğŸ“’ å›ºä»¶ä¿¡æ¯
                - ğŸ’» å¹³å°æ¶æ„: 'x86_64'
                - âš½ å›ºä»¶æºç : 'openwrt'
