name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Generate Changelog
        run: echo "# Good things have arrived" > ${{ github.workspace }}-CHANGELOG.txt
      - name: Release
        uses: ncipollo/release-action@v1
        with:
            name: 'OpenWrt Firmware for ${{ env.FIRMWARE_TAG }}'
            allowUpdates: true
            tag: '${{ env.FIRMWARE_TAG }} for test'
            token: ${{ secrets.GH_TOKEN }}
            artifacts: ${{ github.workspace }}/*
            body: |
                **This is OpenWrt Firmware for ${{ env.FIRMWARE_TAG }}**
                ### ğŸ“’ å›ºä»¶ä¿¡æ¯
                - ğŸ’» å¹³å°æ¶æ„: 'x86_64'
                - âš½ å›ºä»¶æºç : 'openwrt'
